

export class codesdesc{

    static codedes=[
            { code:"P0000" , description:"No trouble code"},  
            {code:"P0001", description:"Fuel Volume Regulator Control Circuit / Open" },
            {code:"P0002", description:"Fuel Volume Regulator Control Circuit Range/Performance" },
            
            {code:"P0003", description:"Fuel Volume Regulator Control Circuit Low" },
            {code:"P0004", description:"Fuel Volume Regulator Control Circuit High " },
            {code:"P0005", description:"Fuel Shutoff Valve Control Circuit / Open " },
            {code:"P0006", description:"Fuel Shutoff Valve Control Circuit Low " },
            {code:"P0007", description:"Fuel Shutoff Valve Control Circuit High " },
            {code:"P0008", description:"Engine Position System Performance - Bank 1 " },
            {code:"P0009", description:"Engine Position System Performance - Bank 1 " },
            {code:"P0010", description:"Intake Camshaft Position Actuator Circuit / Open (Bank 1)" },

            {code:"P0011", description:"Intake Camshaft Position Timing - Over-Advanced (Bank 1)" },
            {code:"P0012", description:"Intake Camshaft Position Timing - Over-Retarded (Bank 1)" },
            {code:"P0013", description:"Exhaust Camshaft Position Actuator Circuit / Open (Bank 1)" },
            {code:"P0014", description:"Exhaust Camshaft Position Timing - Over-Advanced (Bank 1)" },
            {code:"P0015", description:"Exhaust Camshaft Position Timing - Over-Retarded (Bank 1)" },
            {code:"P0016", description:"Crankshaft Position Camshaft Position Correlation Bank 1 Sensor A" },
            {code:"P0017", description:"Crankshaft Position Camshaft Position Correlation Bank 1 Sensor B" },
            {code:"P0018", description:"Crankshaft Position Camshaft Position Correlation Bank 2 Sensor A" },
            {code:"P0019", description:"Crankshaft Position Camshaft Position Correlation Bank 2 Sensor B" },
            {code:"P0020", description:" Intake Camshaft Position Actuator Circuit / Open (Bank 2)" },
            {code:"P0021", description:"Intake Camshaft Position Timing - Over-Advanced (Bank 2)" },
            {code:"P0022", description:"Intake Camshaft Position Timing - Over-Retarded (Bank 2)" },
            {code:"P0023", description:"Exhaust Camshaft Position Actuator Circuit / Open (Bank 2)" },
            {code:"P0024", description:"Camshaft Position B - Timing Over-Advanced or System Performance (Bank 2)" }, 
            {code:"P0025", description:"Exhaust Camshaft Position Timing - Over-Retarded (Bank 2)" },
            {code:"P0026", description:"Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)" },
            {code:"P0027", description:"Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)" },
            {code:"P0028", description:" Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)" },
            {code:"P0029", description:" Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)" },
            {code:"P0030", description:" Heated Oxygen Sensor (H02S) Heater Control Circuit Bank 1 Sensor 1" },
            
            {code:"P0031", description:"Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 1 Sensor 1" },
            {code:"P0032", description:"Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 1 Sensor 1" },  
            {code:"P0033", description:"Turbo/Super Charger Bypass Valve Control Circuit / Open " },
            {code:"P0034", description:"Turbo/Super Charger Bypass Valve Control Circuit Low " },
            {code:"P0035", description:"  Turbo/Super Charger Bypass Valve Control Circuit High" },
            {code:"P0036", description:"Heated Oxygen Sensor (HO2S) Heater Control Circuit Bank 1 Sensor 2 " },
            {code:"P0037", description:"Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 1 Sensor 2 " },
            {code:"P0038", description:" Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 1 Sensor 2 " },
            {code:"P0039", description:" Turbo/Super Charger Bypass Valve Control Circuit Range/Performance" },
            {code:"P0040", description:" Oxygen Sensor Signals Swapped Bank 1 Sensor 1 / Bank 2 Sensor 1 " },
            {code:"P0041", description:" Oxygen Sensor Signals Swapped Bank 1 Sensor 2 / Bank 2 Sensor 2 " },
            {code:"P0042", description:" HO2S Heater Control Circuit (Bank 1, Sensor 3) " },
            {code:"P0043", description:"HO2S Heater Control Circuit Low (Bank 1, Sensor 3) " },
            {code:"P0044", description:"  HO2S Heater Control Circuit High (Bank 1, Sensor 3)" },
            {code:"P0046", description:" Turbocharger/Supercharger Boost Control 'A' Circuit Range/Performance " },
            {code:"P0047", description:"Turbocharger/Supercharger Boost Control 'A' Circuit Low " },
            {code:"P0048", description:" Turbocharger/Supercharger Boost Control 'A' Circuit High " },
            {code:"P0049", description:"Turbo/Super Charger Turbine Overspeed " },

            {code:"P0050", description:"  Heated Oxygen Sensor (HO2S) Heater Circuit Bank 2 Sensor 1" },
            {code:"P0051", description:"Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 1 " },
            {code:"P051B", description:"   Crankcase Pressure Sensor Circuit Range/Performance" },
            {code:"P0052", description:"  Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 1 " },
            {code:"P0053", description:"HO2S Heater Resistance Bank 1 Sensor 1 (PCM) " },
            {code:"P0054", description:" HO2S Heater Resistance Bank 1 Sensor 2 (PCM)" },
            {code:"P0055", description:" HO2S Heater Resistance Bank 1 Sensor 3 (PCM) " },
            {code:"P0056", description:"  Heated Oxygen Sensor (HO2S) 2, Bank 2, Heater control - Circuit Malfunction" },
            {code:"P0057", description:" Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 2" },
            {code:"P0058", description:" Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 2 " }, 
            {code:"P0059", description:" HO2S Heater Resistance (Bank 2, Sensor 1)" },

            {code:"P0060", description:"HO2S Heater Resistance (Bank 2, Sensor 2) " },
            {code:"P0061", description:" HO2S Heater Resistance (Bank 2, Sensor 3)" },
            {code:"P0062", description:"HO2S Heater Control Circuit (Bank 2, Sensor 3) " },
            {code:"P0063", description:"HO2S Heater Control Circuit Low (Bank 2, Sensor 3) " },
            {code:"P0064", description:"HO2S Heater Control Circuit High (Bank 2, Sensor 3) " },
            {code:"P0065", description:"  Air Assisted Injector Control Range/Performance" },
            {code:"P0066", description:" Air Assisted Injector Control Circuit or Circuit Low " },
            {code:"P0067", description:"  Air Assisted Injector Control Circuit or Circuit High" },
            {code:"P0068", description:"MAP / MAF - Throttle Position Correlation " },
            {code:"P0069", description:"  MAP - Barometric Pressure Correlation " },
            {code:"P0070", description:" Ambient Air Temperature Sensor Circuit " },
            {code:"P0071", description:"  Ambient Air Temperature Sensor Range/Performance" },
            {code:"P0072", description:" Ambient Air Temperature Sensor Circuit Low Input" },
            {code:"P0073", description:" Ambient Air Temperature Sensor Circuit High Input" },
            {code:"P0074", description:" Ambient Air Temperature Sensor Circuit Intermittent/Erratic" },
            {code:"P0075", description:" Intake Valve Control Circuit (Bank 2) " },

            {code:"P0076", description:"Intake Valve Control Circuit Low (Bank 2) " },
            {code:"P0077", description:" Intake Valve Control Circuit High (Bank 2) " },
            {code:"P0078", description:"  Exhaust Valve Control Circuit (Bank 2)" },
            {code:"P0079", description:"Exhaust Valve Control Circuit Low (Bank 2) " },
            {code:"P0080", description:" Exhaust Valve Control Circuit High (Bank 2) " },
            {code:"P0081", description:" Intake Valve Control Circuit (Bank 2) " },
            {code:"P0082", description:" Intake Valve Control Circuit Low (Bank 2)" },
            {code:"P0083", description:"Intake Valve Control Circuit High (Bank 2) " },
            {code:"P0084", description:" Exhaust Valve Control Circuit (Bank 2) " },
            {code:"P0085", description:" Exhaust Valve Control Circuit Low (Bank 2) " },
            {code:"P0086", description:"  Exhaust Valve Control Circuit High (Bank 2)" },
            {code:"P0087", description:"Fuel Rail/System Pressure - Too Low " },
            {code:"P0088", description:"Fuel Rail/System Pressure - Too High " },
            {code:"P0089", description:"  Fuel Pressure Regulator Performance" },
            {code:"P0090", description:" Fuel Pressure Regulator Control Circuit " },
            {code:"P0091", description:"Fuel Pressure Regulator Control Circuit Low " },
            {code:"P0092", description:" Fuel Pressure Regulator Control Circuit High " },
            {code:"P0093", description:" Fuel System Leak Detected - Large Leak " },
            {code:"P0094", description:"Fuel System Leak Detected - Small Leak " },
            {code:"P0095", description:"Intake Air Temperature Sensor 2 Circuit " },
            {code:"P0096", description:"  Intake Air Temperature Sensor 2 Circuit Range/Performance" },
            {code:"P0097", description:" Intake Air Temperature Sensor 2 Circuit Low Input" },
            {code:"P0098", description: "Intake Air Temperature Sensor 2 Circuit High Input " },
            {code:"P0099", description:" Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic" },
            
            {code:"P00b7", description:"Engine Coolant Flow Low/Performance " },
            {code:"P0100", description:"Mass or Volume Air flow Circuit Malfunction " },
            

 
 


            {code:"P0101", description:" Mass or Volume Air flow Circuit Range/Performance Problem " },
            {code:"P0102", description:" Mass or Volume Air Flow Circuit low Input" },
            {code:"P0103", description:"Mass or Volume Air flow Circuit High Input " },
            {code:"P0104", description:"Mass or Volume Air flow Circuit Intermittent " },
            {code:"P0105", description:"Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction" },
            {code:"P0106", description:"Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem " },
            {code:"P0107", description:"Manifold Absolute Pressure/Barometric Pressure Circuit Low Input" },
            {code:"P0108", description:"Manifold Absolute Pressure/Barometric Pressure Circuit High Input " },
            {code:"P0109", description:" Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent " },
            {code:"P0110", description:"Intake Air Temperature Circuit Malfunction" },
            {code:"P0111", description:"Intake Air Temperature Circuit Range/Performance Problem " },
            {code:"P0112", description:"Intake Air Temperature Circuit Low Input" },
            {code:"P0113", description:" Intake Air Temperature Circuit High Input" },
            {code:"P0114", description:"Intake Air Temperature Circuit Intermittent " },
            {code:"P0115", description:"Engine Coolant Temperature Circuit Malfunction " },
            {code:"P0116", description:"Engine Coolant Temperature Circuit Range/Performance Problem" },
            {code:"P0117", description:"Engine Coolant Temperature Circuit Low Input " },
            {code:"P0118", description:"Engine Coolant Temperature Circuit High Input" },
            {code:"P0119", description:" Engine Coolant Temperature Circuit Intermittent" },
            {code:"P0120", description:"Throttle Pedal Position Sensor/Switch A Circuit Malfunction" },
            {code:"P0121", description:"Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance Problem" },
            {code:"P0122", description:" Throttle/Pedal Position Sensor/Switch A Circuit Low Input" },
            {code:"P0123", description:" Throttle/Pedal Position Sensor/Switch A Circuit High Input" },
            {code:"P0124", description:" Throttle/Pedal Position Sensor/Switch A Circuit Intermittent" },
            {code:"P0125", description:"  Insufficient Coolant Temperature for Closed Loop Fuel Control" },
            {code:"P0126", description:"Insufficient Coolant Temperature for Stable Operation " },
            {code:"P0127", description:"Intake Air Temperature Too High " },
            {code:"P0128", description:"Coolant Thermostat (Coolant Temp Below Thermostat Regulating Temperature) " },
            {code:"P0129", description:"Barometric Pressure Too Low" },
            {code:"P0130", description:" O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)" },
            {code:"P0131", description:"O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1) " },
            {code:"P0132", description:"O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)" },
            {code:"P0133", description:" O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)" },
            {code:"P0134", description:"O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)" },
            {code:"P0135", description:"O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1) " },
            {code:"P0136", description:" O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)            " },
            {code:"P0137", description:" O2 Sensor Circuit Low Voltage (Bank 1 Sensor 2)" },
            {code:"P0138", description:" O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)            " },
            {code:"P0139", description:" O2 Sensor Circuit Slow Response (Bank 1 Sensor 2)            " },
            {code:"P0140", description:" O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 2)            " },
            {code:"P0141", description:" O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)            " },
            {code:"P0142", description:" O2 Sensor Circuit Malfunction (Bank 1 Sensor 3) " },
            {code:"P0143", description:"  O2 Sensor Circuit Low Voltage (Bank 1 Sensor 3)            " },
            {code:"P0144", description:"O2 Sensor Circuit High Voltage (Bank 1 Sensor 3) " },
            {code:"P0145", description:" O2 Sensor Circuit Slow Response (Bank 1 Sensor 3)            " },
            {code:"P0146", description:"O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 3)            " },
            {code:"P0147", description:"O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 3) " },
            {code:"P0148", description:"Fuel Delivery Error " },
            {code:"P0149", description:"Fuel Timing Error            " },
            {code:"P0150", description:"O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)            " },
            {code:"P0151", description:" O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)            " },
            {code:"P0152", description:"O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)            " },
            {code:"P0153", description:" O2 Sensor Circuit Slow Response (Bank 2 Sensor 1)            " },
            {code:"P0154", description:"O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 1)            " },
            {code:"P0155", description:"O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1) " },
            {code:"P0156", description:" O2 Sensor Circuit Malfunction (Bank 2 Sensor 2)" },
            {code:"P0157", description:" O2 Sensor Circuit Low Voltage (Bank 2 Sensor 2)            " },
            {code:"P0158", description:" O2 Sensor Circuit High Voltage (Bank 2 Sensor 2)            " },
            {code:"P0159", description:"O2 Sensor Circuit Slow Response (Bank 2 Sensor 2)            " },
            {code:"P0160", description:"  O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 2)            " },
            
             


            {code:"P0161", description:" O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)" },
            {code:"P0162", description:"O2 Sensor Circuit Malfunction (Bank 2 Sensor 3) " },
            {code:"P0163", description:" O2 Sensor Circuit Low Voltage (Bank 2 Sensor 3)" },
            {code:"P0164", description:" O2 Sensor Circuit High Voltage (Bank 2 Sensor 3)" },
            {code:"P0165", description:"O2 Sensor Circuit Slow Response (Bank 2 Sensor 3) " },
            {code:"P0166", description:"O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 3) " },
            {code:"P0167", description:" O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 3)" },
            {code:"P0168", description:"Engine Fuel Temperature Too High  " },
            {code:"P0169", description:"Incorrect Fuel Composition " },
            {code:"P0170", description:" Fuel Trim Malfunction (Bank 1) " },
            {code:"P0171", description:" System Too Lean (Bank 1)" },
            {code:"P0172", description:"System Too Rich (Bank 1) " },
            {code:"P0173", description:"Fuel Trim Malfunction (Bank 2) " },
            {code:"P0174", description:"System Too Lean (Bank 2) " },
            {code:"P0175", description:" System Too Rich (Bank 2)" },
            {code:"P0176", description:" Fuel Composition Sensor Circuit Malfunction" },
            {code:"P0177", description:"Fuel Composition Sensor Circuit Range/Performance " },
            {code:"P0178", description:"Fuel Composition Sensor Circuit Low Input " },
            {code:"P0179", description:" Fuel Composition Sensor Circuit High Input" },
            {code:"P018C", description:"Fuel Pressure Sensor B Circuit Low " },
            {code:"P0180", description:" Fuel Temperature Sensor A Circuit Malfunction" },

            {code:"P0181", description:"Fuel Temperature Sensor A Circuit Range/Performance " },
            {code:"P0182", description:"Fuel Temperature Sensor A Circuit low Input   " },
            {code:"P0183", description:"Fuel Temperature Sensor A Circuit Intermittent " },
            {code:"P0184", description:"Fuel Temperature Sensor A Circuit Intermittent " },
            {code:"P0185", description:"Fuel Temperature Sensor B Circuit Malfunction            " },
            {code:"P0186", description:"Fuel Temperature Sensor B Circuit Range/Performance            " },
            {code:"P0187", description:"Fuel Temperature Sensor B Circuit Low Input " },
            {code:"P0188", description:"Fuel Temperature Sensor B Circuit High Input            " },
            {code:"P0189", description:"Fuel Temperature Sensor B Circuit Intermittent   " },
            {code:"P0190", description:"Fuel Rail Pressure Sensor Circuit Malfunction    " },

            
            {code:"P0191", description:"Fuel Rail Pressure Sensor Circuit Range/Performance " },
            {code:"P0192", description:"Fuel Rail Pressure Sensor Circuit Low Input            " },
            {code:"P0193", description:"Fuel Rail Pressure Sensor Circuit High Input  " },
            {code:"P0194", description:"Fuel Rail Pressure Sensor Circuit Intermittent   " },
            {code:"P0195", description:"Engine Oil Temperature Sensor Malfunction            " },
            {code:"P0196", description:"Engine Oil Temperature Sensor Range/Performance            " },
            {code:"P0197", description:"Engine Oil Temperature Sensor Low  " },
            {code:"P0198", description:"Engine Oil Temperature Sensor High  " },
            {code:"P0199", description:"Engine Oil Temperature Sensor Intermittent  " },
            {code:"P0200", description:"Injector Circuit Malfunction            " },



            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " },
            {code:"", description:" " }

    ];
    
}